<?php 

$config['columns'] = [
	"Nome",
	"Eta'",
	"CA",
	"PA",
	"Nazione",
	"Club",
	"Ruolo",
	"Corner",
	"Cross",
	"Dribbling",
	"Finalizzazione",
	"Controllo Palla",
	"Calci Piazzati",
	"Colpo di testa",
	"Tiro da lontano",
	"Rimesse laterali",
	"Marcatura",
	"Passaggi",
	"Rigori",
	"Contrasti",
	"Tecnica",
	"Aggressivita'",
	"Intuito ",
	"Coraggio",
	"Freddezza",
	"Concentrazione",
	"Visione",
	"Decisioni",
	"Determinazione",
	"Fantasia",
	"Carisma",
	"Senza palla",
	"Posizione",
	"Gioco di squadra",
	"Impegno",
	"Accelerazione",
	"Agilita'",
	"Equilibrio",
	"Massima elevazione",
	"Integrita' fisica",
	"Velocita'",
	"Resistenza",
	"Forza",
	"Piede sinistro",
	"Piede destro",
];

$config['exclude_from_player'] = [
	"Nome",
	"Eta'",
	"CA",
	"PA",
	"Nazione",
	"Club",
	"Ruolo",
];